### ISSUE TITLE
False-negative diagnostic in Godot

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/vim-lamp#17]
I have the following wrong diagnostic:
![изображение](https://user-images.githubusercontent.com/22453358/78971522-71618400-7b14-11ea-8f09-6e04b87e0080.png)
It does not appear in vim-lsp and in built-in Godot editor.
I have the following configuration for vim-lamp (it works via TCP, so I used `nc`):
```vim
  call lamp#register('godot', {
        \   'command': ['nc', 'localhost', '6008'],
        \   'filetypes': ['gdscript3'],
        \   'root_uri': { -> lamp#findup(['.git', 'project.godot']) },
        \   'initialization_options': { -> {
        \   } },
        \   'capabilitis': {
        \     'completionProvider': {
        \       'triggerCharacters': ['.', ',']
        \     }
        \   }
        \ })
```
Here is working configuration for vim-lsp:
```vim
autocmd vimrc User lsp_setup call lsp#register_server({
    \ 'name': 'godot',
    \ 'cmd': {server_info->['nc', 'localhost', '6008']},
    \ 'whitelist': ['gdscript3']
    \ })
```
Can I provide more information about the issue?

**Comment by hrsh7th** [comment]
Hm...
Could you tell me the log?

```
    call lamp#config('global.debug', '/tmp/lamp.log')
```

The diagnotisc's related bug is difficult to fix...

**Comment by Shatur** [comment]
[Here](https://pastebin.com/3BwBMPgy) is the generated `/tmp/lamp.log`.

> The diagnotisc's related bug is difficult to fix...

Yes, I understand :(

**Comment by hrsh7th** [comment]
1. lamp received `textDocument/publishDiagnostics` once only and it has one over diagnostics.
- It looks like the right results for me.


2. ignored unknown response but message does not logged.
- Could you test with latest vim-lamp? that improve logging.

**Comment by Shatur** [comment]
[Here](https://pastebin.com/ZCUVdCk8) is the log with latest `vim-lamp`.

**Comment by hrsh7th** [comment]
Thank you for reporting.

I can't understand Godot behavior... Sorry.


1. Could you tell me the log by vim-lsp?
- We may find the somthing.

2. How to setup Godot and that's LSP?

3. Your environment is Linux? Mac? Win?
- Currently, vim-lamp does not support Win.

**Comment by Shatur** [comment]
> Could you tell me the log by vim-lsp?

[vim-lsp.log](https://github.com/hrsh7th/vim-lamp/files/4460667/vim-lsp.log)

> How to setup Godot and that's LSP?

This may be hard :(
LSP support was added to 3.2.2 which will be released around this month. To test it now need to build [Godot](https://github.com/godotengine/godot) and just open the [following](https://github.com/Zoriya/zoriya/blob/master/Characters/Player/Box.gd) file in vim (with configured LSP, of course). I understand that building from source is not a trivial task, so I will try to provide all needed information about he bug.

> Your environment is Linux? Mac? Win?

I use Arch Linux.

**Comment by hrsh7th** [comment]
Thank you for your consideration.

Your settings seem to have one difference between vim-lsp and vim-lamp.
Your `vim-lamp` settings specify `root_uri` but vim-lsp's settings don't it.

**Comment by Shatur** [comment]
Yes, removing `root_uri` fixed the issue, thank you! So, is this configuration problem?

**Comment by hrsh7th** [comment]
https://github.com/godotengine/godot/blob/master/modules/gdscript/language_server/gdscript_language_protocol.cpp#L183

godot seems expects 'root_uri' == 'workspace->root'.

I will investigate VSCode path behavior (I care about trailling slash is needed.

Currently, I think the problem caused by lamp side.

**Comment by hrsh7th** [comment]
Probably, the problem was fixed by https://github.com/hrsh7th/vim-lamp/commit/a858adfa537fbdf33f0901fb359a50f8694e59d5.

Could you test with root_uri?

**Comment by Shatur** [comment]
It worked, thank you!
