### ISSUE TITLE
Automatically highlight references

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/vim-lamp#18]
Currently vim-lamp support `textDocument/documentHighlight`, but in manual way (via `LampDocumentHighlight` and `LampDocumentHighlightClear`). I would like to suggest a neat feature that available in most IDE: highlight an item under cursor automatically (with configurable delay) and clear it after leaving from this item. This how it looks in Qt Creator:
![изображение](https://user-images.githubusercontent.com/22453358/80074010-3e29e680-8551-11ea-8c41-1c0f111befa3.png)
vim-lsp also have this feature, I made a small video to demonstrate how it works:
[![asciicast](https://asciinema.org/a/oWcLio47jxYQo2CwtTtxxO1X1.svg)](https://asciinema.org/a/oWcLio47jxYQo2CwtTtxxO1X1)

**Comment by hrsh7th** [comment]
I think the feature can use https://github.com/itchyny/vim-cursorword instead.

Should I do it with LSP?

**Comment by Shatur** [comment]
Oh, didn't know about it! I think something like cursorword plugin will be enough.
