### ISSUE TITLE
Issue with CMake LSP

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/vim-lamp#21]
I have an issue with [cmake-language-server](https://github.com/regen100/cmake-language-server).
I have the following configuration:

```vim
call lamp#register('cmake-language-server', {
      \   'command': ['cmake-language-server'],
      \   'filetypes': ['cmake'],
      \   'root_uri': { -> lamp#findup(['.git', 'compile_commands.json']) },
      \   'initialization_options': { -> {'buildDirectory': 'build'} },
      \ })
```

`:LampHover` works, but I do not have any completion.

Steps to reproduce:

```bash
git clone https://github.com/Shatur95/akd.git` (sample project)
cd akd
mkdir build
cd build
cmake ..
nvim ../CMakeLists.txt
```

Readme says that completion LSP works with coc.nvim. I also tested vim-lsp, it have the same issue. Can this problem related with vim-lamp?

How can I provide diagnostic? I tried `call lamp#config('global.debug', '/tmp/lamp.log')` from the my previous issue, but it says that the function is unknown.

**Comment by hrsh7th** [comment]
It is the cmake-language-server side problem but I'll fix it.

**Comment by hrsh7th** [comment]
Fixed on latest master.

**Comment by Shatur** [comment]
I tried the latest master, but I still have no completion :(
What was the problem in CMake LSP?

**Comment by hrsh7th** [comment]
The `CompletionItem` that returns from the cmake-language-server is not valid to spec.

Hm... It works on my environment...
![cmake](https://user-images.githubusercontent.com/629908/81905284-79bf4a00-95ff-11ea-82cd-1dda007e6a1b.gif)

**Comment by hrsh7th** [comment]
The LSP spec said `CompletionItem` has `insertText` that is string type or the key itself does not exist.

But the cmake-language-server provided insertText with null.

**Comment by Shatur** [comment]
Thanks for explanations, I will report it to the author.

Weird, the latest master not works for me with the configuration from the first message. I also tried release and latest master of CMake LSP. Can I somehow more infomation for debugging?

**Comment by hrsh7th** [comment]
I tried the configuration of your first message but it worked well.

The following configuration is my worked example.

```
    call lamp#register('cmake-language-server', {
    \   'command': ['cmake-language-server'],
    \   'filetypes': ['cmake'],
    \   'root_uri': { bufnr -> lamp#findup(['build'], bufname(bufnr)) },
    \   'initialization_options': { -> {
    \     'buildDirectory': 'build'
    \   } }
    \ })
```

**Comment by Shatur** [comment]
I tried yours, still not works... Completion from `clangd` works as expected. How do you installed LSP?

**Comment by hrsh7th** [comment]
I've installed `cmake-language-server` via `pip3 install cmake-language-server`.

My `cmake-language-server` version is `0.1.1` (I checked by pip3 list).

**Comment by Shatur** [comment]
Hm... I previously installed it from my package manager. I removed and tried from `pip`. Now I have the following error and LSP do not work at all:
```
Error detected while processing function 6[10]..<SNR>31_send:
line    1:
E900: Invalid channel id
```
All vim plugins are up-to-date.

**Comment by hrsh7th** [comment]
Do you have the `cmake-language-server` on your $PATH?

**Comment by Shatur** [comment]
Oh, sorry, yes, I forgot to update path to `cmake-language-server`. Done. But still the same: LSP working, but without completion :(

I removed all plugins, except vim-compete,  vim-compete-lamp and  vim-lamp. Here is my minimal configuration:
```vim
set completeopt+=menuone,noselect,noinsert
augroup vimrc
  autocmd!
augroup END
call compete#source#lamp#register()
" Initialize servers
autocmd! vimrc User lamp#initialized call s:on_initialized()
function! s:on_initialized()
    call lamp#register('cmake-language-server', {
    \   'command': ['/home/gena/.local/bin/cmake-language-server'],
    \   'filetypes': ['cmake'],
    \   'root_uri': { bufnr -> lamp#findup(['build'], bufname(bufnr)) },
    \   'initialization_options': { -> {
    \     'buildDirectory': 'build'
    \   } }
    \ })

endfunction

" Initialize buffers
autocmd! vimrc User lamp#text_document_did_open call s:on_text_document_did_open()
function! s:on_text_document_did_open() abort
  " Completion
  setlocal omnifunc=lamp#complete
endfunction
```

**Comment by hrsh7th** [comment]
Your setting seems correct so I wonder your `cmake-language-server` version...

**Comment by hrsh7th** [comment]
Could you tell me the `lamp.log`?

**Comment by Shatur** [comment]
I have 0.1.1 from pip. Not works for me even without any plugins with minimal configuration from the above.

Sorry for stupid question, but how can I provide it? I tried `call lamp#config('global.debug', '/tmp/lamp.log')` but I have the following error:
```
Error detected while processing /home/gena/.config/nvim/init.vim:
line   99:
E117: Unknown function: lamp#config
```

**Comment by hrsh7th** [comment]
Hm... Your environment seems broken. `lamp#config` should be exists.

--- Updated ---

If you called `lamp#config` outside of `on_initialized`, you should move `lamp#config` call to `on_initialized`.

**Comment by hrsh7th** [comment]
Aaaaaaaaa! Sorry.
My local `vim-compete-lamp` was changed... I will push soon.

**Comment by Shatur** [comment]
Okay :)

**Comment by hrsh7th** [comment]
I've updated `vim-compete` and `vim-compete-lamp`!

**Comment by Shatur** [comment]
Thanks, works as expected now!

**Comment by hrsh7th** [comment]
Solving your issue is improves my plugins again. Thank you!
