### ISSUE TITLE
Suggestion about hover messages

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/vim-lamp#24]
Currently, hover messages looks in the following way:
![изображение](https://user-images.githubusercontent.com/22453358/83116786-f3ae0380-a0d4-11ea-8717-d9ca6572b7d7.png)
![изображение](https://user-images.githubusercontent.com/22453358/83116798-f6105d80-a0d4-11ea-9275-13f1eb9ec4d0.png)
I suggest to add the current language syntnax highlighting (this will highlight language expressions properly) and add labels for items. How the same diagnostics look in `diagnostics-nvim`:
![изображение](https://user-images.githubusercontent.com/22453358/83116942-2526cf00-a0d5-11ea-93e6-595b3d0cba9b.png)
![изображение](https://user-images.githubusercontent.com/22453358/83116962-2952ec80-a0d5-11ea-8fa4-423b7931ba46.png)

What do you think?

**Comment by hrsh7th** [comment]
It strange. The clangd returns `plaintext` format but other LSP client get `markdown` format.

I searching option of clangd.

**Comment by Shatur** [comment]
It looks like `clangd` is very weird :)

**Comment by hrsh7th** [comment]
It's my easy miss! sorry and thanks.

**Comment by Shatur** [comment]
Hm... Tested the latest master, but still see plaintext in hover from `clangd`.

**Comment by hrsh7th** [comment]
Sorry, fixed it again.

**Comment by Shatur** [comment]
Thank you a lot, now the hover looks awesome:
![изображение](https://user-images.githubusercontent.com/22453358/83120286-818bed80-a0d9-11ea-8ae0-7ce763d48da1.png)

Is it possible to hide \` symbols? I know that this is not related to the plugin itself, just asking :) If I understand correctly, it related to conceal. Is it possible to set it for hover messages?

**Comment by hrsh7th** [comment]
Sorry, I have no idea.

I try to use `tpope/vim-markdown` or `plasticboy/vim-markdown` but both does not support it.

**Comment by Shatur** [comment]
I thought that only I had such a problem :)
Thanks I'll know.

**Comment by Shatur** [comment]
> I try to use tpope/vim-markdown or plasticboy/vim-markdown but both does not support it.

I found [gabrielelana/vim-markdown](https://github.com/gabrielelana/vim-markdown) that have support for it! But it allows to set conceal only globally :(
