### ISSUE TITLE
Add the ability to set custom icons for diagnostics

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/vim-lamp#25]
I suggest to add the ability to change diagnostic signs. Usually LSP plugins have the ability to change it, for example, [vim-lsp](https://github.com/prabirshrestha/vim-lsp#signs), [completion-nvim](https://github.com/haorenW1025/diagnostic-nvim#enabledisable-sign) and [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim/blob/4b35f5d6859ab3d42546192cbede9add59a7435a/doc/LanguageClient.txt#L94).

**Comment by hrsh7th** [comment]
You can set it by following codes.

```viml
call lamp#config('view.sign.error.text', '>>')
call lamp#config('view.sign.warning.text', '>>')
call lamp#config('view.sign.information.text', '>>')
call lamp#config('view.sign.hint.text', '>>')
```

**Comment by Shatur** [comment]
Thank you, just what I need. Will take a look at `lamp#config` first before opening a new issue, sorry :(

**Comment by hrsh7th** [comment]
No need to apologize because I did not write document :)
