### ISSUE TITLE
Jump to next diagnostics

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/vim-lamp#26]
New diagnostics look is just awesome. However, to see information need to go to the error item:
![изображение](https://user-images.githubusercontent.com/22453358/83129422-78088280-a0e5-11ea-85ff-884cef266460.png)
I very like this behavior, but I would like to suggest to add the ability to jump between diagnostics. Something like `:LampNextDiagnostics` and `:LampPreviousDiagnostics`.

**Comment by hrsh7th** [comment]
Implemented.

**Comment by Shatur** [comment]
Thank you, very useful feature!
