### ISSUE TITLE
Insert renaming item text on :LampRename

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/vim-lamp#27]
Currently `:LampRename` requests input with empty text. I suggest to fill this input with the current item name by default. This can be very useful if you want to fix a typo or just extend current name. Most IDE's use the same approach for renaming.

**Comment by Shatur** [comment]
For example, [how it works in VSCode](https://youtu.be/S1Jzrmw0ww8?t=6).

**Comment by hrsh7th** [comment]
Fixed it.

The `textDocument/prepareRename` is bit complex so I missed the return data format.

**Comment by Shatur** [comment]
You are very fast :) Thanks!
