### ISSUE TITLE
Wrong diagnostics on file reopening

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/vim-lamp#28]
For some reason if I reopen file diagnostics will think that this is another file.

**Steps to reproduce**

1. Open any class header, for example [keyboarddaemon.h](https://github.com/Shatur95/akd/blob/master/src/keyboarddaemon.h)
2. Open class implementation and wait for diagnostics.
3. Close and open the same source file again.

**Actual behavior**
It says that all function was already defined:
![изображение](https://user-images.githubusercontent.com/22453358/83184034-82506e00-a131-11ea-8b05-2ad98dad224d.png)

**Expected behavior**
Diagnostics still the same.

**Comment by Shatur** [comment]
Video:
[![asciicast](https://asciinema.org/a/PmcJXEaAy13kc8AK5EgNYaW0O.svg)](https://asciinema.org/a/PmcJXEaAy13kc8AK5EgNYaW0O)

**Comment by hrsh7th** [comment]
Thank you for reporting.
Fixed it.

**Comment by Shatur** [comment]
Now works, thanks!

**Comment by Shatur** [comment]
After this change sometimes after `:bd` it I have an error message that unable to close the latest window. Currently I can't provide steps to reproduce because it happened randomly.

**Comment by hrsh7th** [comment]
Hm... Could you provide full error msg?

I don't use bdelete expricitly.

**Comment by Shatur** [comment]
It prints `E444: Cannot close last window.` twice.

**Comment by Shatur** [comment]
> After this change sometimes after :bd it I have an error message that unable to close the latest window. Currently I can't provide steps to reproduce because it happened randomly.

Can't reproduce anymore, sorry for bothering.
