### ISSUE TITLE
Move lamp functions to autoload

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/vim-lamp#31]
Is it possible to move user-defined vim-lamp initialization functions to autoload?
I trying to create `after/autoload/lamp.vim` but I have the following error (even with the empty file!) at startup:
![изображение](https://user-images.githubusercontent.com/22453358/83518021-8fc77880-a4e2-11ea-8728-970e46ee16aa.png)

**Comment by hrsh7th** [comment]
Hm... It's strange `lamp#config` is already autoload function.

**Comment by Shatur** [comment]
Steps to reproduce:

1. Create an empty `after/autoload/lamp.vim` in vim configuration path.
2. Open the editor.

Will you have an error?

**Comment by hrsh7th** [comment]
I was tested following steps.

1. Create an empty `~/.config/nvim/after/autoload/lamp.vim`
2. Open the editor

But I don't get the error... Hm...

**Comment by Shatur** [comment]
I looked at your configuration, looks like you are using dein. The issue exists for me with native package manager.
I have your packages installed in `~/.local/share/nvim/site/pack/packager/start/`.

**Comment by hrsh7th** [comment]
Sorry, I'm not very familiar to pack feature.
I will study pack feature...

**Comment by Shatur** [comment]
You could try to move all your plugins `~/.local/share/nvim/site/pack/hrsh7th/start/` and see if it works.
For automatic downloading I suggest to take a look at [minpac](https://github.com/k-takata/minpac) or at [vim-packager](https://github.com/kristijanhusak/vim-packager). These plugins depeloped for native packaging. It just for downloading your packages from GitHub and do not needed for a regular startup.

**Comment by Shatur** [comment]
The issue not in vim-lamp.
[This](https://github.com/hrsh7th/vim-vsnip-integ/blob/c195652ec9c99f1bc67a78f2a11baf0474e18eba/autoload/vsnip_integ.vim#L57) line in vim-vnip-integ causes the problem. If I creating `lamp.vim` in `autoload` my custom functions - vsnip think that lamp is already loaded. Is this check is necessary?

**Comment by hrsh7th** [comment]
Oh, I see! Thank you for investigate.
Hm...I consider it.

**Comment by Shatur95** [comment]
Also if move I `lamp` and `lamp-compete` to `opt` folder (folder for optional plugins that can be enabled later with `:packadd`) snippet expansion stop working. I think this related to the `vim-vnip-integ` enabling mechanism. It would be nice if it will support native packaging too.

**Comment by Shatur** [comment]
What if replace

```vim
if g:vsnip_integ_config.lamp && s:exists('autoload/lamp.vim')
```
with
```vim
if g:vsnip_integ_config.lamp && exists('g:loaded_lamp') && g:loaded_lamp == v:true
```

I tested, it works for me. Note that `s:exists` and `exists` is different :)
It looks like such check is faster, more reliable and solves my issue. Similar check can be done for other plugins too.
If you agree, I can sand you a PR.

**Comment by Shatur** [comment]
Oh, I see that you already a [PR](https://github.com/hrsh7th/vim-vsnip-integ/pull/19) that will fix the issue automatically because it changes this logic.
So, I closing this issue because it is not related to the `vim-lamp`.

**Comment by hrsh7th** [comment]
Thank you for investigate it.
I will fix it on vim-vsnip-integ.
